### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'update_id'

### ISSUE THREAD

**Issue by beshr-eldebuch** [jojo786/Sample-Python-Telegram-Bot-AWS-Serverless-PTBv20#1]
python-telegram-bot Version: 20.4
Python: 3.8.10

Unable to run the same on AWS Lambda, it raises the following error: it seems that update_id is required and one of its dependency is not updated.
![image](https://github.com/jojo786/Sample-Python-Telegram-Bot-AWS-Serverless-PTBv20/assets/38144217/57dc4b92-cbc7-4fc7-9188-ad9c6e867437)

**Comment by jojo786** [comment]
I'm unable to replicate that.

Here is what I did now to get this to deploy successfully, using python 3.8 on Lambda:

1. clone this repo to a new folder
2. Update template.yaml to `Runtime: python3.8`
3. Update ptb_lambda.py with the value of the bots token
4. sam build
5. sam deploy --guided
6. Use value of TelegramApi from the output of sam deploy, and update the bots WebHook Url
7. the bot works as expected.

Although it does not look like an issue due to the python version, what made you think you using Python: 3.8.10 in Lambda?  Because when I look at the Lambda logs using `sam logs --stack-name Sample-Python-Telegram-Bot-AWS-Serverless-v20 --region eu-west-1` I see this: 

2023/08/12/[$LATEST]2c899bbb04f2475481529d0e07a5c245 2023-08-12T11:12:51.915000 INIT_START Runtime Version: python:3.8.v24

Is there any specific reason you not using the latest python v11?

**Comment by beshr-eldebuch** [comment]
@jojo786 
Thanks for the reply.
Pythons version is just a preference, whereas almost all the apps that I'm currently working on are 3.8.10. Nothing else.

Regarding the issue, I've followed a different path for deployment:
1. Deployment was done through Serverless with the appropriate settings.
2. Connected the Telegram bot with the AWS Lambda using Microsoft Bot Framework (since I was doing the same but for Skype, it was only a click)
3. Requests are hitting the lambda correctly, but nothing is working so far. I am checking this issue further. I'm suspecting that it has something to do with the Microsoft Bot Framework. I'll see. 
4. For now, as a temp solution, I've just done this --> 
 
```python
payload= json.loads(event["body"])
payload["update_id"] = 1
```

Thanks for your time with this. I'll check the issue in more detail.

**Comment by beshr-eldebuch** [comment]
Yep, Microsoft Bot Framework changes the structure of the message that the bot should receive
I've just followed up with the following webhook configs, and it's working now. Thanks mate :100: 
https://github.com/jojo786/Sample-Python-Telegram-Bot-AWS-Serverless-PTBv20#:~:text=Update%20your%20Telegram,on%20that%20API.
